### PR TITLE
Column match test

### PR DESCRIPTION
**Pull request by hcavalle**
This PR adds in support for discarding csv records when strict mode is disabled and the field count of a record does not match the expected column count. This includes test cases for these scenarios in both strict and non-strict mode. Review carefully as errors here could result in unintentionally lost records.

Thanks for all the good work on this one @amareesh86!

### CODE REVIEW

**Comment by amareesh86** [comment]
:+1:

**Comment by kuujo** [comment]
We should be using the slf4j logging API instead of log4j. Log4j is really an implementation of an slf4j logger.

```Logger LOGGER = LoggerFactory.getLogger(...)```

**Comment by kuujo** [comment]
We're handling strict parsing issues and throwing related exceptions in two different places. The `strict` flag is passed to `CsvRecordReader` and Apache CSV has a strict parsing mode that it uses. If additional exceptions need to be thrown I think they should be thrown from there and wrapped in a `TapException` on the scheme level.

**Comment by kuujo** [comment]
I'm not sure how the strut parsing in Apache CSV reconciles with the scheme. This looks good other than that, so if there's an issue with moving it this can be merged.

**Comment by hcavalle** [comment]
Awesome, I'll make the logger change and look at the scheme in relation to Apache CSV's strict mode and try to see if it's an 'easy' change...

**Comment by kuujo** [comment]
I think the logger needs to be changed in other places too

**Comment by hcavalle** [comment]
Maybe I'll worry about the logger separately?

**Comment by kuujo** [comment]
Sounds good to me!

**Comment by hcavalle** [comment]
I have to admit defeat, I don't see a way to avoid passing `strict` to `CsvRecordReader` dealing with exceptions in the scheme. I'm sure there is a way, but eluding me for now and I've spent enough time on it!

**Comment by kuujo** [comment]
Apache CSV already handles column count checks for us if we want it to. That's what this line is about: https://github.com/datascienceinc/cascading.csv/blob/master/src/main/java/com/datascience/hadoop/CsvRecordReader.java#L66

Currently, what that line is doing actually looks like a bug. It should say:
```
if (!record.isConsistent()) {
  if (strict) {
    throw new SomethingWrongWithParsingException("!");
  }
  return next(key, value);
}
```

The `CsvScheme` can then catch `SomethingWrongWithParsingException` (or something obviously more aptly named than that) and wrap it in `TapException`

**Comment by hcavalle** [comment]
Gotcha, I totally misunderstood. That makes sense, I'll test it.

**Comment by kuujo** [comment]
Actually, I realized I think we *have* to move the consistency check into `CsvRecordReader`. I don't think there's anything wrong with the consistency check that's happening here. The reason it has to be done in `CsvRecordReader` is because the `CsvScheme` actually allows its output `Fields` to differ from the actual columns in the CSV file. So, what we need to check is that the columns we're expecting in the CSV file are actually present, not that the fields we're expecting to output are.

https://github.com/datascienceinc/cascading.csv/blob/column-match-test/src/main/java/com/datascience/cascading/scheme/CsvScheme.java#L727

This logic should allow `Fields` to represent the `columns` in a different order than that in which they appear in the file, but it should also allow `Fields` to represent a subset of the `columns` as well. For instance, a CSV file with the columns `id`, `first`, and `last` should be able to be parsed with `new Fields("id")`, and indeed we should be testing this behavior (I think it was on the todo list). So, at a high level the `CsvRecordReader` is the component that understands what the CSV file should look like, and the `CsvScheme` knows only what the output values should look like and how to map those to `Fields`.

**Comment by kuujo** [comment]
https://github.com/datascienceinc/cascading.csv/blob/column-match-test/src/main/java/com/datascience/cascading/scheme/CsvScheme.java#L614

Note that in the event that the user provides headers in the `CSVFormat` and `Fields`, this logic checks only that each field is *present* in the `CSVFormat` headers, not that they're equal in size.

**Comment by kuujo** [comment]
Awesome :+1:

**Pull request merged**
